-- V22: Extend workspaces for SaaS multi-tenant

ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS plan VARCHAR(20) DEFAULT 'STARTER' CHECK (plan IN ('STARTER', 'PROFESSIONAL', 'ENTERPRISE', 'CUSTOM'));
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'TRIAL' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'TRIAL', 'PAST_DUE'));
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMPTZ;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS subscription_ends_at TIMESTAMPTZ;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS stripe_customer_id VARCHAR(100);
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS custom_domain VARCHAR(255);
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS max_agents INTEGER DEFAULT 3;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS max_contacts INTEGER DEFAULT 1000;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS primary_color VARCHAR(20) DEFAULT '#2563EB';

CREATE INDEX IF NOT EXISTS idx_workspaces_plan ON workspaces(plan);
CREATE INDEX IF NOT EXISTS idx_workspaces_status ON workspaces(status);
CREATE INDEX IF NOT EXISTS idx_workspaces_slug ON workspaces(slug);