spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_dev
    username: crm_user
    password: crm_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ""

# Swagger habilitado solo en dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    com.crm: DEBUG
    org.springframework.security: DEBUG
